CREATE TABLE _migrations ();
CREATE TABLE messages ();
CREATE TABLE stars ();
ALTER TABLE _migrations ADD COLUMN id_ INTEGER;
ALTER TABLE messages ADD COLUMN author_id NUMERIC;
ALTER TABLE messages ADD COLUMN channel_id NUMERIC;
ALTER TABLE messages ADD COLUMN id NUMERIC;
ALTER TABLE messages ADD COLUMN last_known_star_count INTEGER;
ALTER TABLE messages ADD COLUMN sb_msg_id NUMERIC;
ALTER TABLE stars ADD COLUMN message_id NUMERIC;
ALTER TABLE stars ADD COLUMN user_id NUMERIC;
ALTER TABLE _migrations ALTER COLUMN id_ SET NOT NULL;
ALTER TABLE messages ALTER COLUMN author_id SET NOT NULL;
ALTER TABLE messages ALTER COLUMN channel_id SET NOT NULL;
ALTER TABLE messages ALTER COLUMN id SET NOT NULL;
ALTER TABLE messages ALTER COLUMN last_known_star_count SET NOT NULL;
ALTER TABLE stars ALTER COLUMN message_id SET NOT NULL;
ALTER TABLE stars ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE _migrations ADD CONSTRAINT __migrations_id__primary_key PRIMARY KEY ( id_ );
ALTER TABLE messages ADD CONSTRAINT _messages_id_primary_key PRIMARY KEY ( id );
ALTER TABLE stars ADD CONSTRAINT _stars_message_id_user_id_primary_key PRIMARY KEY ( message_id , user_id );